POST {{endpoint}}/blogposts
Accept: application/json
Content-Type: application/json

{
  "title": "test",
  "content": "Das ist ein Test"
}

> {%
  client.test("BlogPosts returned", () => {
    client.assert(response.status === 201);
  });
%}

###

POST {{endpoint}}/blogposts
Accept: application/json
Content-Type: application/json

{
  "content": "Das ist ein Test"
}

> {%
  client.test("BlogPosts returned", () => {
    client.assert(response.status === 400);
  });
%}
